### ISSUE TITLE
Requests to the path endpoint not working

### ISSUE THREAD

**Issue by timadair** [Senzing/rest-api-client-ng#9]
The API is including the toString of the SzEntityIdentifiers instead of using their contents.

**To Reproduce**
Use any of the EntityGraphService.findPathByEntityId methods

**Comment by docktermj** [comment]
Pull Requests:

1. https://github.com/Senzing/rest-api-client-ng/pull/10
1. https://github.com/Senzing/rest-api-client-ng/pull/11
